version: '3'
services:
  postgres:
    image: postgres:12.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1819
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server/config:/app/config
      - ./server/src:/app/src
      - ./server/test:/app/test
      - ./server:/app
    ports:
      - '5000:5000'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '8080:8080'
